In [10]:
import numpy as np

In [11]:
invent= np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])

In [12]:
invent.shape

(5, 4)

In [13]:
invent.dtype

dtype('int32')

In [14]:
invent.size

20

In [15]:
invent.itemsize

4

In [16]:
invent.size*invent.itemsize

80

In [17]:
invent=invent+20

In [18]:
invent

array([[120, 220, 170, 320],
       [ 70,  80,  60, 100],
       [320, 420, 370, 520],
       [220, 270, 240, 290],
       [100, 110,  90, 120]])

In [20]:
invent[2]-=10

print(invent)

[[120 220 170 320]
 [ 70  80  60 100]
 [300 400 350 500]
 [220 270 240 290]
 [100 110  90 120]]


In [21]:
invent[1]*=2

print(invent)

[[120 220 170 320]
 [140 160 120 200]
 [300 400 350 500]
 [220 270 240 290]
 [100 110  90 120]]


In [22]:
max_cap=1000

In [23]:
per_stock=(invent/max_cap)*100

print(per_stock)

[[12. 22. 17. 32.]
 [14. 16. 12. 20.]
 [30. 40. 35. 50.]
 [22. 27. 24. 29.]
 [10. 11.  9. 12.]]


In [24]:
total=np.sum(invent,axis=1)

print(total)

[ 830  620 1550 1020  420]


In [25]:
total_loc=np.sum(invent,axis=1)

print(total_loc)

[ 830  620 1550 1020  420]


In [27]:
total_proloc=np.sum(invent,axis=1)

print(total_proloc)

[ 830  620 1550 1020  420]


In [28]:
max_stock=np.argmax(total_proloc)

print(max_stock)

2


In [29]:
total_pro=np.sum(invent,axis=0)

print(total_pro)


[ 880 1160  970 1430]


In [30]:
min_stock=np.argmin(total_pro)

print(min_stock)

0


In [31]:
avg_pro = np.mean(invent, axis=1)

print(avg_pro)

[207.5 155.  387.5 255.  105. ]


In [32]:
pro_2=invent[1]

print(pro_2)

[140 160 120 200]


In [33]:
loc_3_stock = invent[:, 2]
print(loc_3_stock)


[170 120 350 240  90]


In [34]:
select_loc2_stock = invent[2:4, [1, 3]]  
print(select_loc2_stock)

[[400 500]
 [270 290]]


In [35]:
selected_stock = invent[:3, :2]
print(selected_stock)

[[120 220]
 [140 160]
 [300 400]]


In [36]:
selected_last2_stock = invent[-2:, -2:] 
print(selected_last2_stock)

[[240 290]
 [ 90 120]]


In [37]:
stock_pro_5_loc_3 = invent[4, 2]
print(stock_pro_5_loc_3)

90


In [38]:
products = [0, 3]  
locations = [0, 2] 

selected_stock_indx = invent[products, locations]
print(selected_stock_indx)

[120 240]


In [39]:
invent[1, 3] = 100
print(invent)


[[120 220 170 320]
 [140 160 120 100]
 [300 400 350 500]
 [220 270 240 290]
 [100 110  90 120]]
